server:
  port: 3001
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.8.11:1521/crhwskh
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: crh_user
    password: cairenhui
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location:
pagehelper:
  helper-dialect: oracle
  reasonable: true
