server:
  port: 3001
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.1.154:1521/crhwskh
    driver-class-name: oracle.jdbc.OracleDriver
    username: crh_user
    password: cairenhui
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  rabbitmq:
    addresses: '172.16.1.172:5672'
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        concurrency: 5
        max-concurrency: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: oracle
  reasonable: true
jwt:
  signing:
    key: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
logging:
  config: 'classpath:logback.xml'